package com.example.trackcap.database.movimientos.gastos

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import com.example.trackcap.database.cards.CardItemEntity

@Entity(
    tableName = "gastos_items",
    foreignKeys = [ForeignKey(
        entity = CardItemEntity::class,
        parentColumns = ["id"],
        childColumns = ["cardId"],
        onDelete = ForeignKey.CASCADE
    )]
)
data class GastoItemEntity(
    // id autogenerated
    @ColumnInfo(name = "id")
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "category")
    val category: String,

    @ColumnInfo(name = "amount")
    val amount: Double,

    @ColumnInfo(name = "date")
    val date: Long,

    @ColumnInfo(name = "paymentMethod")
    val paymentMethod: String,

    @ColumnInfo(name = "cardId")
    val cardId: Int? = null
)