package com.example.trackcap.database.movimientos.ingresos

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "ingresos_items")
data class IngresoItemEntity(
    // id autogenerated
    @ColumnInfo(name = "id")
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "category")
    val category: String,

    @ColumnInfo(name = "amount")
    val amount: String,

    @ColumnInfo(name = "date")
    val date: Long
)